optimizer : {
  type: AdamW,
  kwargs: {
  lr: 0.001,
  weight_decay: 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 200,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'train'}},
  val : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'val'}},
  test : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'test'}}}

model : {
  NAME: PointNetS,
  cls_dim: 72,
  encoder_dims: 512,
  input_format: subject,
  fc_layer: 1
}

npoints: 20
total_bs: 1
step_per_update : 1
max_epoch : 200
grad_norm_clip : 10