optimizer : {
  type: Adam,
  kwargs: {
  lr: 0.001,
  betas: [0.9, 0.999],
  weight_decay: 0
}}

scheduler: {
  type: StepLR,
  kwargs: {
    step_size: 20,
    gamma: 0
}}

dataset : {
  train : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'train'}},
  val : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'val'}},
  test : { _base_: cfgs/dataset_configs/HCP105.yaml, 
            others: {subset: 'test'}}}

model : {
  NAME: TractCloud,
  k: 20,
  k_global: 500,
  num_classes: 72
}

npoints: 20
total_bs: 1024
step_per_update: 1
max_epoch: 60